= A hidden guarantee of the IIFE
:hp-tags: JavaScript

The http://stackoverflow.com/questions/8228281/what-is-the-function-construct-in-javascript[Immediately Invoked Function Expression] is a common way to encapsulate scope in JavaScript. Since there are more fun things to do than to dig into and debug someone else's code, we want to prevent messing up things located e.g. in the same file. However, I recently spotted one more interesting fact about the IIFE.

Everyone in frontend had to work with a large, few hundred or even thousand of lines long file called somewhere along _scripts.js_. It usually contains jQuery plugins' initialization, data gathering via Ajax and lots of other, random stuff.

If you need to add something to it and *it is planned to be refactored and extracted into a separate file*, the IIFE is a way to go. It will encapsulate your new, shiny piece of code that you have to put into this dirty mess. Despite looking a little weird:

[source,javascript,options="nowrap"]
----
$(document).ready(function() {
  $('.slider').sliderPlugin();
  
  //...
  
  (function() {
    //shiny code
  })();
});
----

*it's a great investment for further refactoring*. And I think it's the most important lesson here. The IIFE block says:

*whoever you are, you can cut and paste this code into a separate .js file and everyone is gonna be just fine*.