= OOP in AngularJS #1 - defining a class
:hp-tags: AngularJS, JavaScript


When it comes to object oriented programming, JavaScript is a little bit weird in comparison with other (preferably C-like) languages. The same holds true while working with AngularJS.

The topic has been already covered in the Internet multiple times. If you're looking for a comprehensive article, just google it up. This blog post is intended to be used more like a handnote or a cheatsheet, so I'll try to keep it extremally concise.

---

The `Task` class used in the following example represents an object with two properties: a textual content and a (theoretically) read-only array of hashtags. The latter property is automatically regenerated by extracting hashtags from the task's content via a regex expression.

Long story short, defining a class in AngularJS looks as follows:
[source,javascript]
----
myApp.factory('Task', function () {
  // defining a constructor
  function Task(content) {
    // initialization of the object happens here
    this.setContent(content);
  }

  // defining public members
  Task.prototype = {
    setContent: function (value) {
      this._content = value;

      //looking for hashtags
      var regexp = /\B\#\w\w+\b/g;
      this._tags = this._content.match(regexp);
    },
    getContent: function () {
      return this._content;
    },
    getTags: function () {
      return this._tags;
    }
  };

  // defining a static method
  Task.restore = function (data) {
    return new Task(data._content);
  };

  return Task;
});
----

The class has to be injected as any other module to a controller:
[source,javascript]
----
myApp.controller('MainController', ['$scope', 'Task', function ($scope, Task) {
  $scope.task = new Task('Lorem lipsum #hashtag');
  $scope.anotherOne = Task.restore({ _content: 'Another one'});
}]);
----