= Project configurations + Publish Profiles + Web.configs
:hp-tags: .NET, C#, Visual Studio, ASP.NET MVC

Recently we faced a need of developing a multilingual ASP.NET MVC project to two, separate Web Deploy targets. Both instances differed only by the language of the user interface. Since I'm quite proud of how convenient the deployment became thanks to our solution, I decided to describe it briefly in this blog post. 

== Prepare project configurations

For the sake of demonstration, let's assume our web application will be deployed to three servers in three language variants: Polish, English and German.

First of all, let's create project configurations. Go to the solution's _Configuration Manager_:

image::http://placehold.it/400x200[align=center]

Then create a new project configuration using the dropdown menu in a _Configuration_ columnn next to the project's name:

image::http://placehold.it/400x200[align=center]

Name it appriopriately. _ReleasePL_ sounds good to me, since it'll be a configuration for Polish version of the project. Probably you'd like to create a new solution configuration and copy settings from the _Release_. Create variants _ReleaseEN_ and _ReleaseDE_ as well at that point.

image::http://placehold.it/400x200[align=center]

== Web.configs and their transforms

Hit the _Add Config Transform_ item from the Web.config's context menu in the _Solution Explorer_. It'll generate configuration variants for each of the project configurations which have been just created.



language

if Culture? no no no

fdafad

[source, XML]
----
<webConfig goes="here" />
----

[source, xml]
----
<publishProfile goes="here" />
----


== Where are my three hours?