= Let's start Get Noticed!
:hp-tags: Get Noticed, Daj się poznać

I was thinking about joining the http://dajsiepoznac.pl[Get Noticed! (Daj Się Poznać!) competition] last year, but didn't manage to find enough free time to do so. I couldn't miss this opportunity again so this year I decided to take my chances. Briefly speaking, it is a contest for programmers during which you are oblidged to not only write the code but also document your progress with blog posts and spread the word in social media. You can learn more on the http://dajsiepoznac.pl[contest's page].

The series of posts under the Get Noticed tag will be dedicated exactly for this purpose. I will describe the development, reasoning behind the decisions I will take (or no reasoning as well) and all of the other matters that are more or less connected with the project.

Speaking about the project, it will be a *JavaScript quiz with a competitive note*. The main use case of this application is during conferences, meetups or workshops (like http://nodeschool.io/lodz[NodeSchool]). The speaker will show the presentation with questions considering JavaScript and its +++<strike>fucked up</strike>+++ _unique_ features. The attendands are meant to give answers using their smartphones. Obvoiusly, a person that gives the most correct answers wins.

The code is https://github.com/zbicin/go-home-js[available on GitHub], however there is not much there by now. If you are curious about the project progress and details concerning its implementation, stay tuned for next posts. According to the rules of the contest, there should be at least two of them per week, which means plenty of writing.

Keep your fingers crossed and let's do this!


